[package]
name = "text_analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "txtzer"
path = "bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
